---
title: "Shiny Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    theme: cosmo
    vertical_layout: fill
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(ggplot2)
library(ggmap)
library(maps)
library(mapdata)
library(leaflet)
library(httr)
library(plotly)
```

```{r}
organ <- GET("https://health.data.ny.gov/resource/km5a-7zrs.csv?$limit=10000") %>% 
  content("parsed") %>%
  janitor::clean_names() %>%
  filter(county != "TOTAL NYS" & county != "Out of State" & county != "Unknown") %>%
  mutate(year = as.character(year)) %>%
  mutate(month = as.character(month)) %>%
  mutate(dummy_day = as.character("01")) %>%
  mutate(date = (str_c(year, month, dummy_day, sep = "-"))) %>%
  mutate(date = as.Date(date, "%Y-%m-%d"))

organ_tidy = 
  organ %>% 
  mutate(county = tolower(county)) %>% 
  mutate(county = recode(county,  'cattauragus' = 'cattaraugus')) %>% 
  group_by(county, year) %>% 
  summarise(mean_enrolled = mean(eligible_population_enrolled)) %>% 
  ungroup()

ny_county = map_data("county")  %>% 
  filter(region == "new york") %>% 
  as.tibble() %>% 
  rename(county = subregion)

ny_county_combined = 
full_join(organ_tidy, ny_county, by = 'county')

organ_df = 
  organ %>% 
  separate(location, c("lat", "long"), sep = ",") %>% 
  mutate(long = str_replace(long, "\\)", ""),
         long = as.numeric(long)) %>% 
  mutate(lat = str_replace(lat, "\\(", ""),
         lat = as.numeric(lat)) %>% 
  group_by(county, long, lat) %>% 
  summarise()
```

Column {.sidebar}
-----------------------------------------------------------------------

```{r}
years = ny_county_combined %>% distinct(year) %>% pull()

# selectInput widget
radioButtons("year_choice", label = h3("Select year"),
            choices = years, selected = "2018")
```



Column {data-width=950}
-----------------------------------------------------------------------

### The heatmap of registry porportion

```{r}
renderPlotly({
  ny_county_combined =
    ny_county_combined %>% 
    filter(year == input$year_choice)
  map = 
  ggplot() + 
  geom_polygon(data = ny_county_combined, 
               aes(x = long, 
                   y = lat, 
                   group = group, 
                   fill = mean_enrolled)) +
  geom_path(data = ny_county_combined, 
            aes(x = long, 
                y = lat,
                group = group), 
            color = "white", 
            size = 0.1) +
  geom_text(data = organ_df, 
            aes(x = long, 
                y = lat, 
                label = county),
            size = 2.5,
            color = "white") +
  labs(x = 'Longitude', 
       y = 'Latitude', 
       title = 'The registry porportion map for different counties in the New York State', 
       fill = '% Enrollment') +
  coord_equal() +
  theme_void()+
  viridis::scale_fill_viridis(option = "magma", direction = -1)
  ggplotly(map)
})

```

Column {data-width=50}
-----------------------------------------------------------------------

### Homepage
<a target="_blank" href="https://jackyan0320.github.io/p8105_final_project/index.html">
  <h4>Home page</h4>
</a>
